language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - g++-6
            - gcc-6
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="brew update && brew install gcc6 || brew link --overwrite gcc; CC=gcc && CXX=g++"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  # Check versions first
  - $CC -v && $CXX -v
  - cmake --version
  - ./utils/fetch_deps.sh
  # then build
  - mkdir build && cd build && cmake .. && make

